server:
  port: 10080
spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/high
    driver-class-name: com.mysql.jdbc.Driver
    username: root
mybatis-plus:
  configuration:
    local-cache-scope: statement
    cache-enabled: false